# Programs
terminal = "kitty"
file_manager = "dolphin"
browser = "librewolf"

# Theming
theme = "Breeze"
icon_theme = "Papirus"
cursor = "Vimix-white-cursors"
cursor_size = "24"
wallpaper = "~/Pictures/wallpaper.jpg"

laptop_mode = "false"
