# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  services.xserver.videoDrivers = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  hardware.graphics = {
    # Enable OpenCL
    extraPackages = with pkgs; [
      # rocmPackages.clr.icd
    ];
    enable32Bit = true;
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  fileSystems."/mnt/triangle" =
    {
      device = "/dev/disk/by-label/Triangle";
      fsType = "btrfs";
    };

  fileSystems."/mnt/octagon" =
    {
      device = "/dev/md0";
      fsType = "ext4";
    };

  # Raid drives utils
  environment.systemPackages = with pkgs; [
    mdadm
  ];

  swapDevices =
    [{ device = "/dev/disk/by-label/NIXSWAP"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.swraid.enable = true;
  boot.swraid.mdadmConf = ''
    ARRAY /dev/md/crumbly-pc:0 level=raid1 num-devices=2 metadata=1.2 name=crumbly-pc:0 UUID=b7f88a79:c8cbcbdb:b9c72930:261591d8 devices=/dev/sda1,/dev/sdb1
    PROGRAM=/home/crumbly/.config/scripts/mdadm_program
  '';
}
