#!/usr/bin/env bash
# Returns the status of any key with a status light

KEY=$1

# Basically OR all status lights
# Keyboard lights aren't managed by the keyboard but
# there might be some bugs regarding syncing the lights
# between multiple keyboards
ON=0
while read line
do
    if [ $line = "1" ]; then
        ON=1
        # We can exit early since when even one status light is on
        # the key must be enabled (hopefully :D)
        break
    fi
done < <(cat /sys/class/leds/input*::$KEY/brightness)
echo $ON
