# Disable the default Hyprpaper splash (over the wallpaper)
splash = false

# Hyprpaper is configured to use whatever wallpaper
# is symlinked to `~/.config/wallpaper.png`
# Wallpaper can be selected by editing
# the `wallpaper` symlink in `bombadil.toml`
wallpaper {
    monitor =
    path = ~/.config/wallpaper.png
    fit_mode = cover
}
