#!/bin/bash

get_brightness () {
    echo $(brightnessctl -m -d intel_backlight | awk -F, '{print substr($4, 0, length($4)-1)}' | tr -d '%')
}

set_brightness () {
    brightnessctl set $1'%'
}

if [ "$1" = "get" ]; then
    get_brightness
elif [ "$1" = "set" ]; then
    set_brightness $2
fi

