#!/usr/bin/env bash

music () {
    playerctl -i plasma-browser-integration "$1"
}

if [ "$1" = "play" ]; then
    music "play-pause"
elif [ "$1" = "previous" ]; then
    music "previous"
elif [ "$1" = "next" ]; then
    music "next"
fi
