export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export EDITOR="nvim"
export VISUAL="nvim"

# Programs that don't follow the XDG spec >:(
export LESSHISTFILE="$XDG_STATE_HOME"/less/history

export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export PATH="$PATH:$CARGO_HOME/bin"

export GOPATH="$XDG_DATA_HOME"/go

export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python

export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java -Dawt.useSystemAAFontSettings=lcd"
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

export VSCODE_PORTABLE="$XDG_DATA_HOME"/vscode
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet

export WINEPREFIX="$XDG_DATA_HOME"/wine

export STACK_ROOT="$XDG_DATA_HOME"/stack

export MATHEMATICA_USERBASE="$XDG_CONFIG_HOME"/mathematica

export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
