# Enable Starship prompt
eval "$(starship init zsh)"
# Initialize zoxide
eval "$(zoxide init --cmd cd zsh)"
# Fzf integration
eval "$(fzf --zsh)"

# Inspired by https://www.youtube.com/watch?v=ud7YxC33Z3w
# Plugin manager
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit.zinit.git"
[ ! -d "$ZINIT_HOME" ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d "$ZINIT_HOME/.git" ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"

# Load plugin manager
source "${ZINIT_HOME}/zinit.zsh"

# Plugins
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode

zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions

zinit light Aloxaf/fzf-tab

# OMZ pluggins
zinit snippet OMZP::git
zinit snippet OMZP::command-not-found

# Cache completions
autoload -Uz compinit && compinit -d "${ZDOTDIR}/zcompdump-${ZSH_VERSION}"

# Replay cached completions
zinit cdreplay -q

# Keybindings
# Set keybindings to Vim mode
bindkey -v
# Make switching between modes faster
export KEYTIMEOUTE=1

# Forward and backward searching in history
# with something typed in
# bindkey '^p' history-search-backward
# bindkey '^n' history-search-forward

# History
[ ! -d "$XDG_STATE_HOME/zsh" ] && mkdir -p "$XDG_STATE_HOME/zsh"
HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=10000
SAVEHIST=$HISTSIZE
# No duplicates
HISTDUP=erase
# Don't overwrite history
setopt appendhistory
# Share history between terminal sessions
setopt sharehistory
# Commands that start with a space won't be saved to history
setopt hist_ignore_space
# Ignore duplicates in search and don't save them
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_find_no_dups

# Completion styling
# Match lower case characters to upper case characters
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Enable 256-color mode
export TERM="xterm-256color"

# Go up certain amount of directories
up () {
  if [ -z $1 ]; then
    cd ..
  elif [ $1 -gt 0 ]; then
    let count=1
    cdstr=".."
    while [ $count -lt $1 ]; do
      cdstr="$cdstr/.."
      let count=count+1
    done
    cd $cdstr
  else
    echo "Argument must be a positive integer."
  fi
}

# Git
# Not needed for now because of OMZ git plugin
#for al in `git --list-cmds=alias`; do
#    alias g$al="git $al"
#done

# Open file with the default program
alias open="xdg-open"

# Go to .dotfiles directory
alias dotfiles="cd ~/.dotfiles"
alias dots=dotfiles

# List files
alias ls="eza --icons=auto"
alias ll="ls -alh"
alias sl="sl -e"

alias gpp="g++"
alias gppwp="g++ -Wall -pedantic"
alias gppwpa="g++ -Wall -pedantic -fsanitize=address"

alias vim="nvim"
alias nv="nvim"

alias cat="bat"

# Use custom hsts cache file location
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

# Use custom home
alias adb='HOME="$XDG_DATA_HOME"/android adb'
